name: products_management
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dropdown: ^1.0.0+hotfix.1
  flutter_screenutil: ^5.0.1
  flutter_secure_storage: ^5.0.2
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^0.23.0+1
  form_field_validator: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  like_button: ^2.0.4
  rxdart: ^0.27.3
  shared_preferences: ^2.0.9
  syncfusion_flutter_datepicker: ^19.3.57

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 500
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 700

    - family: Baltica
      fonts:
        - asset: fonts/Baltica-Bold.ttf
